version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: notify to slack
          command: |
            curl -X POST \
            $SLACK_WEBHOOK_URL \
            -H 'content-type: application/json' \
            -d '{
              "text": "Build started!"
            }'
      - run:
          name: install aws
          command: |
            sudo pip install awscli
            aws --version
      - run:
          command: cd nginx && docker build -t $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/inamuu-test01:$CIRCLE_SHA1 .
      - run:
          command: cd ~/repo/.circleci/ && ./deploy.sh